logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"           # 모든 actuator 엔드포인트 노출
      base-path: /actuator

  metrics:
    enable:
      jvm: true
      system: true
      tomcat: true
      process: true
      hikaricp: true
      jdbc: true
    tags:
      application: ${spring.application.name}

  endpoint:
    health:
      show-details: always


spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5435/my_api
    driver-class-name: org.postgresql.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create #실무에선 none, validated
    show-sql: false
    open-in-view: false #OSIV = false(성능 매우 중요합니다)